### ISSUE TITLE
Order execution issue

### ISSUE THREAD

**Issue by kienle371999** [marigold-dev/batcher#207]
When I looked through the codebase, I found some issues in `order_book`.

- The order book only filtered the `bids` and `asks` orders based on the `clearing_tolerance`. For example, the `clearing_volume` is `EXACT` and the EXACT `bids` and `asks` orders are selected. However, I think we can select MINUS , EXACT `bids` and EXACT, PLUS `asks` in this situation.
- The `exchange_rate` is not updated based on the `clearing_tolerance`.

Can you confirm this, @glottologist?

**Comment by Hakimba** [comment]
> For example, the clearing_volume is EXACT and the EXACT bids and asks orders are selected. **However, I think we can select MINUS , EXACT bids and EXACT, PLUS asks in this situation.**

I'm not sure to understand, in fact when the clearing tolerance is EXACT, we want to select the EXACT, PLUS bids, because if if i asked for buying at PLUS, EXACT is obviously ok for me. And we want to select MINUS, EXACT for the ask, because if i asked for selling at MINUS, EXACT is also obvioulsy ok for me as i will sell at a greater price than asked.

And thats exactly what the function **trigger_filtering_orders** do.

```
[@inline]
let trigger_filtering_orders (orderbook : t) (clearing : clearing) : t =
  let (f_bids,f_asks) =
    match clearing.clearing_tolerance with
     | MINUS ->
       ((fun (_: order) -> true),
       (fun (order : order) -> order.tolerance = MINUS))
     | EXACT ->
       ((fun (order : order) ->
         order.tolerance = EXACT || order.tolerance = PLUS),
        (fun (order : order) ->
         order.tolerance = MINUS || order.tolerance = EXACT))
     | PLUS ->
       ((fun (order : order) -> order.tolerance = PLUS),
       (fun (_:order) -> true))
  in
  let new_bids = filter_orders orderbook.bids f_bids in
  let new_asks = filter_orders orderbook.asks f_asks in

  {orderbook with bids = new_bids; asks = new_asks}
```

In particular, this part of the function : 

```
 | EXACT ->
       ((fun (order : order) ->
         order.tolerance = EXACT || order.tolerance = PLUS),
        (fun (order : order) ->
         order.tolerance = MINUS || order.tolerance = EXACT))
```

**Comment by glottologist** [comment]
Yes this is correct.

**Comment by kienle371999** [comment]
@Hakimba Yup, I misunderstood this when I raised this issue.
